# default configuration
baseURL = "http://examplesite.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "iMobilize Ltd"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.home]]
URL = ""
name = "Home"
weight = 1

[[menu.about]]
URL = "about"
name = "About"
weight = 2

[[menu.portfolio]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.contact]]
URL = "contact"
name = "Get In Touch"
weight = 4

[[menu.blog]]
URL = "packages"
name = "Packages"
weight = 5

[[menu.blog]]
URL = "blog"
name = "Blog"
weight = 6




# default parameters
[params]
home = "Home"
logo = "images/iMobilize_white.png"
# theme color
theme_color = "#41228e"
# contact info
phone = "0333 090 2401"
email = "info@imobilize.co.uk"
address = "Kemp House, 160 City Road, London, EC1V 2NX"
# meta description
author = "iMobilize ltd"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# baidu site verification
baidu_site_verification = "" #Your verification code
# baidu analytics
baidu_analytics_id = "" #Your ID
# copyright
copyright = "© Copyright 2016 iMobilize Ltd. All rights reserved. Company Number 06780564 Registered in England & Wales."


# preloader
[params.preloader]
enable = true
preloader = "images/259.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/imobilizeltd"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/imobilizeltd/"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/imobilizeltd"